services:
  mysql:
    image: mysql:lts
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=notemeadow
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql
  
  backend:
    build: ./backend
    ports:
      - 8080:80
    volumes:
      - ./backend/uploads:/var/www/html/uploads
    environment:
      - CLIENT_URL=http://localhost:1234

  frontend:
    build: ./frontend
    ports:
      - 1234:80