services:
  mysql:
    image: mysql:lts
    platform: linux/x86_64
    volumes:
      - ./data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - TZ=Asia/Ho_Chi_Minh
      - MYSQL_DATABASE=notemeadow
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_HOST=mysql

  y-websocket:
    build:
      context: ./y-websocket
    ports:
      - 4321:4321

  backend:
    build:
      context: ./backend
    ports:
      - 8080:80
    volumes:
      - ./backend/uploads:/var/www/html/uploads
    env_file:
      - .env