services:
  backend:
    build:
      dockerfile: Dockerfile.prod

  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=${API_URL}
        - WS_URL=${WS_URL}
    ports:
      - 1234:80