services:
  backend:
    build:
      dockerfile: Dockerfile.prod

  frontend:
    build:
      context: ./frontend
      args:
        - API_URL=http://backend
        - WS_URL=ws://y-websocket:4321
    ports:
      - 1234:80